// CPC Transport Manager (Passenger) - Question bank
// Generado a partir de CPC-tests/*.txt. Se va ampliando tema a tema.
window.CPC_TEMAS = {
"02": { title: "Tema 2 - Business Law", questions: [
{q:"In contract law the term 'consideration' means:", options:["Each party must behave fairly to the other","The parties must take legal advice before entering into the contract","A 14-day period following the signing of a contract","A right or benefit accruing to each party from the contract"], correct:3, exp:"'Consideration' es uno de los 4 elementos esenciales de un contrato válido (oferta, aceptación, consideration, intención de crear relación legal). Significa que cada parte debe dar o recibir algo de valor a cambio de lo que promete la otra."},
{q:"Which of the following statements relating to a public limited company are correct? 1. Minimum of two directors. 2. Not necessary to appoint a company secretary. 3. All PLCs must have accounts externally audited. 4. Nominal share capital not less than €25,000. 5. Cannot begin business until a Trading Certificate is issued.", options:["2 and 3 only","1 and 4 only","1, 3 and 5 only","2, 3 and 4 only"], correct:2, exp:"Una PLC necesita mínimo 2 directores, debe auditar sus cuentas externamente, y no puede operar hasta que la CRO emita el Trading Certificate. La 2 es falsa (sí necesita Company Secretary)."},
{q:"Which of the following items of information must a limited company display on all its business letters?", options:["Authorised share capital","Name of the Company Secretary","Name of managing director","The address of the company's registered office"], correct:3, exp:"La ley exige mostrar nombre legal, número de registro y la dirección del domicilio social en toda la papelería comercial."},
{q:"Which items must be submitted to the Companies Registration Office when forming a limited company? 1. Statement of compliance 2. Statement of capital 3. Name of accountants 4. Memorandum of association 5. Articles of association 6. Corporation Tax registration.", options:["2, 3, 5","1, 4, 6","3, 4, 5, 6","1, 2, 4 and 5 only"], correct:3, exp:"Se presentan: declaración de cumplimiento, capital inicial, Memorandum y Articles. El nombre de contables y el alta de Corporation Tax no forman parte de la constitución."},
{q:"When satisfied that the requirements of the Companies Act 2014 have been met, the Companies Registration Office will issue a new company with:", options:["A memorandum of association","A certificate of incorporation","A prospectus","The articles of association"], correct:1, exp:"El Certificate of Incorporation confirma que la empresa existe legalmente — es su 'partida de nacimiento'."},
{q:"Which statements concerning private limited companies are correct? 1. Trading name ends with PLC. 2. Must be at least one director. 3. May invite public to buy shares. 4. May invite public to invest in debentures. 5. Trading name ends with Limited.", options:["2 and 4","2 and 5","1 and 3","1, 3 and 4"], correct:1, exp:"Una Ltd privada necesita solo 1 director y su nombre termina en 'Limited'. No puede ofrecer acciones ni debentures al público."},
{q:"In the event of a members voluntary winding up of a limited company, the directors must file with the Companies Registration Office a declaration of:", options:["Total debt","Bankruptcy","Solvency","Insolvency"], correct:2, exp:"Es una liquidación VOLUNTARIA porque la empresa puede pagar sus deudas — los directores firman una Declaration of Solvency."},
{q:"An operator advertises a vehicle at €8500 ono. Offers are received between €8000 and €8800. Legally, the operator:", options:["Must accept first offer of €8500","Can accept or reject any offer","Must accept first over €8500","Must accept highest offer"], correct:1, exp:"Un anuncio es una 'invitation to treat', no una oferta vinculante — el vendedor puede aceptar o rechazar libremente cualquier oferta."},
{q:"For a valid contract to exist, which of the following factors must be present?", options:["Verbal offer and written acceptance","Written offer and written acceptance","Written offer, acceptance, consideration","Offer, acceptance and consideration"], correct:3, exp:"Los 3 elementos esenciales son oferta, aceptación y consideration — no hace falta que sea por escrito."},
{q:"Under the Companies Act 2014, a private limited company:", options:["Is not permitted to offer either shares or debentures to the public for cash","May offer shares but not debentures to the public","May offer debentures but not shares","May offer both"], correct:0, exp:"Una Ltd privada tiene prohibido ofrecer al público tanto acciones como debentures a cambio de dinero."},
{q:"A partnership which is created to give members the benefit of limited liability must have:", options:["One general partner only","One limited partner only","One general partner and one limited partner","Two general and two limited"], correct:2, exp:"Una limited partnership necesita al menos un general partner (gestiona, responde con su patrimonio) y un limited partner (solo invierte)."},
{q:"The most common remedy for a breach of contract is:", options:["Damages","An injunction","Imprisonment","A fine"], correct:0, exp:"El remedio civil habitual por incumplimiento de contrato es 'damages' (indemnización económica)."},
{q:"When creating a limited company a statement confirming that shareholders have limited liability can be found in the company's:", options:["Certificate of Incorporation","Memorandum of Association","Statement of Capital","Articles of Association"], correct:3, exp:"Los Articles of Association recogen que la responsabilidad de los socios está limitada a lo invertido."},
{q:"A company's articles of association must contain details of which of the following? 1. Authorised share capital 2. Rules governing appointment of directors 3. Company registration number 4. Rights of shareholders at general meetings 5. Names of founding members.", options:["1 only","2 and 3","2 and 4 only","1, 3 and 5"], correct:2, exp:"Los Articles regulan cómo se nombran los directores y los derechos de voto de los socios en las juntas."},
{q:"Which position is required by a public limited company but is optional for a private limited company?", options:["Chief Executive Officer","Company Secretary","Company Director","Chairman of the board"], correct:1, exp:"Una PLC siempre necesita Company Secretary; en una Ltd pequeña puede ser más flexible."},
{q:"For how many years does the Companies Act require a limited company to maintain copies of their accounting records?", options:["3 years","5 years","6 years","10 years"], correct:2, exp:"El Companies Act 2014 exige conservar los registros contables 6 años."},
{q:"If directors deliberately set out to defraud creditors, they could face terms of imprisonment of up to 10 years. This criminal offence is known as:", options:["Insider trading","Reckless trading","Fraudulent trading","Breach of contract"], correct:2, exp:"'Fraudulent trading' es dirigir el negocio con intención deliberada de estafar a los acreedores."},
{q:"When distributing money raised by the disposal of assets during a liquidation, which of the following has the highest priority for payment?", options:["Unsecured debts","Liquidator's fees and expenses","Preferential debts (wages)","Fixed-Charge (secured) creditors"], correct:3, exp:"Orden de prelación: 1º acreedores con garantía real (fixed-charge), 2º gastos del liquidador, 3º deudas preferentes (salarios), 4º garantía flotante, 5º sin garantía."},
{q:"What is the main difference in the internal structure between a Sole Trader and a Limited Company?", options:["Sole traders must file accounts with the CRO","Sole traders have unlimited liability for business debts","Sole traders pay Corporation Tax","Sole traders must have a Memorandum of Association"], correct:1, exp:"El autónomo responde de las deudas con todo su patrimonio personal (responsabilidad ilimitada); en una Ltd los socios solo arriesgan lo invertido."},
{q:"At what point does a contract acceptance sent by post become legally complete?", options:["When the letter is received by the offeror","When the letter is read","On posting the letter","24 hours after posting"], correct:2, exp:"La 'postal rule': el contrato se perfecciona en el momento de echar la carta al correo, no cuando se recibe."},
{q:"Which group of people do not have full contractual capacity under Irish law?", options:["Company directors","People under 18 (minors)","Shareholders","Sole traders"], correct:1, exp:"Los menores de 18 años no tienen capacidad contractual plena — sus contratos son en general anulables."},
{q:"What is the key rule regarding dividend payments for ordinary and preference shares?", options:["Both are paid equally","Ordinary shareholders are paid first","Ordinary shareholders will not receive any dividend until preference shareholders have been paid","Preference shares do not receive dividends"], correct:2, exp:"Las preference shares tienen preferencia de cobro; los accionistas ordinarios solo cobran si sobra beneficio después."},
{q:"A Designated Activity Company (DAC) must:", options:["Have a minimum of 149 members","Only trade within the parameters of the designated activities listed in its objects clause","Have its name ending in PLC","Issue shares to the general public"], correct:1, exp:"Una DAC mantiene una cláusula de objeto social limitado, a diferencia de la Ltd normal (capacidad ilimitada)."},
{q:"When an external auditor examines a company's accounts, who is their primary duty towards?", options:["The directors","The company secretary","The Companies Registration Office","The shareholders"], correct:3, exp:"El deber principal del auditor es hacia los accionistas, para protegerlos de posibles irregularidades de los directores."},
{q:"What is the fundamental difference between a debenture holder and a shareholder?", options:["Debenture holders are paid interest, not dividends, and have no voting rights","Debenture holders own the company","Shareholders receive interest","Debenture holders vote at the AGM"], correct:0, exp:"Un debenture holder es un acreedor (le prestó dinero a la empresa), cobra interés fijo y no vota."},
{q:"If a shareholder cannot attend a general meeting, how can they legally pass their voting rights to someone else?", options:["By calling the company secretary","By appointing a proxy","By selling their shares","By emailing the director"], correct:1, exp:"Puede nombrar un 'proxy' (representante) mediante un formulario formal para votar en su nombre."},
{q:"Which type of company is legally obliged to hold an Annual General Meeting (AGM) each year?", options:["A sole trader","A partnership","A Public Limited Company (PLC)","A Private Limited Company"], correct:2, exp:"Las PLC están obligadas a celebrar AGM anual; muchas Ltd pequeñas pueden estar exentas si todos los socios lo acuerdan."},
{q:"At what stage is an offer no longer possible to withdraw?", options:["After 24 hours","After the offeree has accepted it","Once it is written down","Before the offeree reads it"], correct:1, exp:"Una oferta se puede retirar libremente antes de la aceptación; una vez aceptada, ya existe contrato vinculante."}
]}
};
